### ISSUE TITLE
GlitchFilter seed and slices doesn't do anything.

### ISSUE THREAD

**Issue by Dai696** [pixijs/filters#185]
Glitch filter appears to be partially broken. It doesn't slice or change seed.

**Comment by TTA1eu** [comment]
hi @Dairnon, i have ur same problem, i checked the solution u mentioned but since i'm pretty new to pixijs i m not sure where is the file to fix. im using pixijs from link now:

  <script src="https://cdnjs.cloudflare.com/ajax/libs/pixi.js/5.1.3/pixi.min.js"></script>           // for main pixi js
  <script src="https://cdn.jsdelivr.net/npm/pixi-filters@2.6.1/dist/pixi-filters.js"></script>         // for advanced filters like glitch

im supposed to directly put the pixi library in my assets? in this case i cant find the andvanced filters in the library from pixijs.com or nowhere.
could u be so gentle to help me to get this working, simply i need to find the file mentioned by @bigtimebuddy, fix as he suggest and import in my assets, i don t know where to find it and how to import it.
really thanks if u can help me and sorry for my english
